//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdw.Testapplication.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Cdw.Service", ConfigurationName="WCFService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Cdw.Service/IService/GetLoginContext", ReplyAction="Cdw.Service/IService/GetLoginContextResponse")]
        Cdw.Objects.LoginContext GetLoginContext();
        
        [System.ServiceModel.OperationContractAttribute(Action="Cdw.Service/IService/Login", ReplyAction="Cdw.Service/IService/LoginResponse")]
        Cdw.Objects.AuthenticationResponse Login(Cdw.Objects.AuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cdw.Service/IService/CreateComputer", ReplyAction="Cdw.Service/IService/CreateComputerResponse")]
        Cdw.Objects.OperationResult CreateComputer(Cdw.Objects.Computer computer);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cdw.Service/IService/GetUser", ReplyAction="Cdw.Service/IService/GetUserResponse")]
        Cdw.Objects.OperationResult GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cdw.Service/IService/GetSoftware", ReplyAction="Cdw.Service/IService/GetSoftwareResponse")]
        Cdw.Objects.SoftwareItem[] GetSoftware();
        
        [System.ServiceModel.OperationContractAttribute(Action="Cdw.Service/IService/GetNextAvailableComputerName", ReplyAction="Cdw.Service/IService/GetNextAvailableComputerNameResponse")]
        Cdw.Objects.OperationResult GetNextAvailableComputerName(string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cdw.Service/IService/GetComputer", ReplyAction="Cdw.Service/IService/GetComputerResponse")]
        Cdw.Objects.OperationResult GetComputer(string computername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Cdw.Testapplication.WCFService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Cdw.Testapplication.WCFService.IService>, Cdw.Testapplication.WCFService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cdw.Objects.LoginContext GetLoginContext() {
            return base.Channel.GetLoginContext();
        }
        
        public Cdw.Objects.AuthenticationResponse Login(Cdw.Objects.AuthenticationRequest request) {
            return base.Channel.Login(request);
        }
        
        public Cdw.Objects.OperationResult CreateComputer(Cdw.Objects.Computer computer) {
            return base.Channel.CreateComputer(computer);
        }
        
        public Cdw.Objects.OperationResult GetUser(string username) {
            return base.Channel.GetUser(username);
        }
        
        public Cdw.Objects.SoftwareItem[] GetSoftware() {
            return base.Channel.GetSoftware();
        }
        
        public Cdw.Objects.OperationResult GetNextAvailableComputerName(string prefix) {
            return base.Channel.GetNextAvailableComputerName(prefix);
        }
        
        public Cdw.Objects.OperationResult GetComputer(string computername) {
            return base.Channel.GetComputer(computername);
        }
    }
}
